### ISSUE TITLE
Implement component: Header

### ISSUE THREAD

**Issue by trouni** [trouni/predictor-vue#15]
![Predictor_Mockups__Copy_](https://user-images.githubusercontent.com/34345789/118350461-d5fdd680-b591-11eb-9df4-26a62fb46146.jpg)

**Comment by dmbf29** [comment]
how do i make a drowdown without Boostrap? 😂

**Comment by trouni** [comment]
Haha you could just revert to the standard [`<select>` HTML tag](https://www.w3schools.com/tags/tag_select.asp) and [reset the styling](https://stackoverflow.com/questions/1895476/how-do-i-style-a-select-dropdown-with-only-css).

**Comment by dmbf29** [comment]
🤯
<img width="843" alt="Screen Shot 2021-05-17 at 19 29 36" src="https://user-images.githubusercontent.com/25542223/118474617-39306a00-b746-11eb-8da8-73f22399aefc.png">

**Comment by trouni** [comment]
How about [this library](https://vue-select.org/)? Adds 19.9kb, but seems reasonable?

**Comment by dmbf29** [comment]
TBH, I was thinking an actual dropdown is pointless if we stay consistent with the Leadeboard design. We could do it like this: 
<img width="376" alt="Screen Shot 2021-05-17 at 20 21 10" src="https://user-images.githubusercontent.com/25542223/118480732-97ad1680-b74d-11eb-92c8-8445cb81b0d8.png">

**Comment by trouni** [comment]
Yup, consistency is definitely a good idea. We can always update that component later on if we have better UX ideas.
