### ISSUE TITLE
Photo Upload Btn disappeared 

### ISSUE THREAD

**Issue by dmbf29** [trouni/predictor-vue#201]
<img width="442" alt="Screen Shot 2022-11-22 at 15 42 08" src="https://user-images.githubusercontent.com/25542223/203243156-b9531179-6575-4cbd-adea-c08433413b4e.png">

The red button is in the top left. Not sure how it got hidden.

**Comment by trouni** [comment]
Oh right, I fixed the overflow hidden for the avatar (there was a white square around the circle). I'm assuming the button was in the overflowing area.

**Comment by trouni** [comment]
Fixed in #203
