### ISSUE TITLE
Fix color of pill in ResultCard while the match is in progress

### ISSUE THREAD

**Issue by trouni** [trouni/predictor-vue#236]
Should probably be grey.

<img width="376" alt="Octacle" src="https://user-images.githubusercontent.com/34345789/205951026-346fda19-468e-4d81-8e3c-1732fc17fdf6.png">

**Comment by jjmountain** [comment]
@trouni I was thinking the same. Greyt minds think alike?

**Comment by trouni** [comment]
Haha yeah, and I think the flags should have full opacity as well.

**Comment by jjmountain** [comment]
#238
