### ISSUE TITLE
Leaderboard Navigation

### ISSUE THREAD

**Issue by dmbf29** [trouni/predictor-vue#38]
We need to put the name in the subheader and be able to change from one leaderboard to the next 

<img width="447" alt="Screen Shot 2021-05-26 at 21 12 41" src="https://user-images.githubusercontent.com/25542223/119657829-5b716880-be67-11eb-8684-3ad9c6da2f8d.png">

**Comment by trouni** [comment]
Closing this issue, suggested solution in #50.
